version: 2
jobs:
  build:
    working_directory: ~/.
    docker:
      - image: circleci/python
    steps:
      - run:
          name: Test this
          command: 'echo hello'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build