version: 2
jobs:
  build:
    working_directory: ~/builder
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Test this
          command: 'python ~/builder/Main.py'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build